# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc_message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11rpc_message.proto\x12\x08pkg_grpc\" \n\rClientMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cMessageReply\x12\x0f\n\x07message\x18\x01 \x01(\t2W\n\x0fSecurityService\x12\x44\n\x0fReceiveMessages\x12\x17.pkg_grpc.ClientMessage\x1a\x16.pkg_grpc.MessageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CLIENTMESSAGE']._serialized_start=31
  _globals['_CLIENTMESSAGE']._serialized_end=63
  _globals['_MESSAGEREPLY']._serialized_start=65
  _globals['_MESSAGEREPLY']._serialized_end=96
  _globals['_SECURITYSERVICE']._serialized_start=98
  _globals['_SECURITYSERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
