# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc_message_pb2 as rpc__message__pb2


class SecurityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveMessages = channel.unary_unary(
                '/pkg_grpc.SecurityService/ReceiveMessages',
                request_serializer=rpc__message__pb2.ClientMessage.SerializeToString,
                response_deserializer=rpc__message__pb2.MessageReply.FromString,
                )


class SecurityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=rpc__message__pb2.ClientMessage.FromString,
                    response_serializer=rpc__message__pb2.MessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pkg_grpc.SecurityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecurityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pkg_grpc.SecurityService/ReceiveMessages',
            rpc__message__pb2.ClientMessage.SerializeToString,
            rpc__message__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
