// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: rpc_message.proto
#ifndef GRPC_rpc_5fmessage_2eproto__INCLUDED
#define GRPC_rpc_5fmessage_2eproto__INCLUDED

#include "rpc_message.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace pkg_grpc {

class SecurityService final {
 public:
  static constexpr char const* service_full_name() {
    return "pkg_grpc.SecurityService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::pkg_grpc::MessageReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkg_grpc::MessageReply>> AsyncReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkg_grpc::MessageReply>>(AsyncReceiveMessagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkg_grpc::MessageReply>> PrepareAsyncReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pkg_grpc::MessageReply>>(PrepareAsyncReceiveMessagesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage* request, ::pkg_grpc::MessageReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage* request, ::pkg_grpc::MessageReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pkg_grpc::MessageReply>* AsyncReceiveMessagesRaw(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pkg_grpc::MessageReply>* PrepareAsyncReceiveMessagesRaw(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::pkg_grpc::MessageReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkg_grpc::MessageReply>> AsyncReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkg_grpc::MessageReply>>(AsyncReceiveMessagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkg_grpc::MessageReply>> PrepareAsyncReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pkg_grpc::MessageReply>>(PrepareAsyncReceiveMessagesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage* request, ::pkg_grpc::MessageReply* response, std::function<void(::grpc::Status)>) override;
      void ReceiveMessages(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage* request, ::pkg_grpc::MessageReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pkg_grpc::MessageReply>* AsyncReceiveMessagesRaw(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pkg_grpc::MessageReply>* PrepareAsyncReceiveMessagesRaw(::grpc::ClientContext* context, const ::pkg_grpc::ClientMessage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ReceiveMessages_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ReceiveMessages(::grpc::ServerContext* context, const ::pkg_grpc::ClientMessage* request, ::pkg_grpc::MessageReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ReceiveMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ReceiveMessages() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ReceiveMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReceiveMessages(::grpc::ServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReceiveMessages(::grpc::ServerContext* context, ::pkg_grpc::ClientMessage* request, ::grpc::ServerAsyncResponseWriter< ::pkg_grpc::MessageReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ReceiveMessages<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ReceiveMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ReceiveMessages() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::pkg_grpc::ClientMessage, ::pkg_grpc::MessageReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::pkg_grpc::ClientMessage* request, ::pkg_grpc::MessageReply* response) { return this->ReceiveMessages(context, request, response); }));}
    void SetMessageAllocatorFor_ReceiveMessages(
        ::grpc::MessageAllocator< ::pkg_grpc::ClientMessage, ::pkg_grpc::MessageReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::pkg_grpc::ClientMessage, ::pkg_grpc::MessageReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ReceiveMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReceiveMessages(::grpc::ServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReceiveMessages(
      ::grpc::CallbackServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ReceiveMessages<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ReceiveMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ReceiveMessages() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ReceiveMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReceiveMessages(::grpc::ServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ReceiveMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ReceiveMessages() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ReceiveMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReceiveMessages(::grpc::ServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestReceiveMessages(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ReceiveMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ReceiveMessages() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ReceiveMessages(context, request, response); }));
    }
    ~WithRawCallbackMethod_ReceiveMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ReceiveMessages(::grpc::ServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ReceiveMessages(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ReceiveMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ReceiveMessages() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pkg_grpc::ClientMessage, ::pkg_grpc::MessageReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::pkg_grpc::ClientMessage, ::pkg_grpc::MessageReply>* streamer) {
                       return this->StreamedReceiveMessages(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ReceiveMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ReceiveMessages(::grpc::ServerContext* /*context*/, const ::pkg_grpc::ClientMessage* /*request*/, ::pkg_grpc::MessageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedReceiveMessages(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pkg_grpc::ClientMessage,::pkg_grpc::MessageReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ReceiveMessages<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ReceiveMessages<Service > StreamedService;
};

}  // namespace pkg_grpc


#endif  // GRPC_rpc_5fmessage_2eproto__INCLUDED
